### ISSUE TITLE
Action Animations 

### ISSUE THREAD

**Issue by mhl787156** [FARSCOPE-UKRAS-Festival-Game-Dev/Robot-Explore-Game#46]
Give some visual + sound feedback on doing an action. e.g.

- Drill - sound of drill (two sounds success/failure), mild camera shake 
- Camera - shutter sound, flash of light
- Take Sample - robot arm moving (?)/ motor sounds, dialog box of [sampling...] coming up

**Comment by jhird11** [comment]
@mhl787156 Are you happy to complete this?

**Comment by mhl787156** [comment]
Yes I can give it a go at some point! Might need some help for the visual things

**Comment by jhird11** [comment]
Yeah I didn't get around to it today #74 Added the functionality we talked about for triggers letting the robot know if it's actions did anything

**Comment by jhird11** [comment]
I have an idea for the photo which which would be kinda cool. 

So you click the camera
![image](https://user-images.githubusercontent.com/47662879/121137802-f63a5180-c82e-11eb-999a-2fd8c3b06c8e.png)

Then there's like this flash
![image](https://user-images.githubusercontent.com/47662879/121137837-00f4e680-c82f-11eb-9e07-08ddd5aeadb7.png)

Then the picture starts growing from the centre 

![image](https://user-images.githubusercontent.com/47662879/121138019-326db200-c82f-11eb-9a4f-4c4fe68e25dd.png)

Pops up on the screen like photo

![image](https://user-images.githubusercontent.com/47662879/121138408-909a9500-c82f-11eb-88fe-c9a9f57c3383.png)

Then because this is a game not a nunnery we could have some fun text like
![image](https://user-images.githubusercontent.com/47662879/121138165-57622500-c82f-11eb-8cd7-49133ef9dbdb.png)

OR

![image](https://user-images.githubusercontent.com/47662879/121138299-73fe5d00-c82f-11eb-832f-b7781bebc8d9.png)

**Comment by jhird11** [comment]
It will hide after a second or so and then stop playing if you tap it.

If we have time we could add these to the journal. Might have to put a gap on it to avoid spam

**Comment by mhl787156** [comment]
OMG I love the idea hahaha we'll see how far I get with it :p 
It would be good to get a high res photo or something - it depends on where the extra shaders were placed I guess 
Also I can tell you've spent a loooong time thinking about this xD
